config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users

  resources :brands do
    collection { post :import }
    resources :sizes, except: [:show] do
      collection { post :import }
    end
  end

  resources :sizes, only: [:destroy] do
    collection { post :import }
  end

  resources :size_imports, only: [:new, :create]

  get 'search/' =>'pages#search'

  get 'about/' => 'pages#about'

end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
	before_action :authenticate_user!
	before_action :is_admin?
	before_action :find_brand

  def new
  	@size = @brand.sizes.build()
  end

  def create
  	@size = @brand.sizes.build(size_params)
  	if @size.save
  		flash[:success] = "Size added."
  		redirect_to @brand
  	else
  		render :new
  	end
  end

  def edit
  	@size = @brand.sizes.find(params[:id])
  	render 'new'
  end

  def update
  	@size = @brand.sizes.find(params[:id])
  	if @size.update_attributes(size_params)
  		flash[:success] = "Size updated."
  		redirect_to @brand
  	else
  		render 'new'
  	end
  end

  def destroy
  	@brand.sizes.find(params[:id]).destroy
  	flash[:success] = "Size destroyed."
  	redirect_to @brand
  end

  def index
    @sizes = @brand.sizes
    respond_to do |format|
      format.html
      format.csv do 
        send_data @sizes.to_csv, filename: "#{@brand.slug}_sizes.csv"
      end
    end
  end

  def import
    Size.import(params[:file], limit_to: { brand_id: @brand.id })
    redirect_to @brand
  end

  private

  def size_params
  	params.require(:size).permit(:name, :max_height, :min_height, :max_weight, :min_weight)
  end

  def find_brand
  	@brand = Brand.friendly.find(params[:brand_id])
  end
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/sizes/_search_result.html.erb
<div class="search_result row center">
	<div class="col-md-3">
		<% if size.brand_profile_picture %>
			<div class="brand_profile_picture">
				<a href=<%= brand_path size.brand %>>
					<%= image_tag size.brand_profile_picture, height: 140, width: 140 %>
					<h4><span><%= size.brand_name %></span></h4>
				</a>
			</div>
		<% else %>
		<h2><%= link_to size.brand_name, size.brand %></h4>
		<% end %>
	</div>
	<div class="col-md-3 size">
		<h2><%= size.name %></h2>
	</div>
	<div class="col-md-6">
		<h5>Height</h5>
		<%= size.height_range %>
		<h5>Weight</h5>
		<%= size.weight_range %>
	</div>
</div>

app/views/sizes/_size.html.erb
<tr>
	<td>
		<% if current_user.admin? %>
			<%= link_to size.name, edit_brand_size_path(size.brand, size) %>
		<% else %>
			<%= size.name %>
		<% end %>
	</td>
	<td><%= size.height_range %></td>
	<td><%= size.weight_range %></td>
	<% if current_user.admin? %>
		<td>
			<%= link_to 'delete', brand_size_path(size.brand, size), 
			                      method: :delete, confirm: "Delete this size?" %>
		</td>
	<% end %>
</tr>

app/views/sizes/edit.html.erb
<h1>Sizes#edit</h1>
<p>Find me in app/views/sizes/edit.html.erb</p>

app/views/sizes/new.html.erb
<div class="row">
	<div class="col-md-8">
		<h2><%= params[:action].titleize %> Size</h2>
		<%= form_for [@brand, @size] do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>
		  <div class="form-group">
		  	<%= f.label :name, "Name" %>
		  	<%= f.text_field :name, class: "form-control", placeholder: "e.g. A1" %>
		  </div>

		  <div class="row">
			  <div class="form-group col-md-3">
			  	<%= f.label :min_height, "Minimum Height (inches)" %>
			  	<%= f.number_field :min_height, class: "form-control" %>
			  </div>

			  <div class="form-group col-md-3 col-md-offset-3">
			  	<%= f.label :max_height, "Maximum Height (inches)" %>
			  	<%= f.number_field :max_height, class: "form-control" %> 
			  </div>
		  </div>

		  <div class="row">
			  <div class="form-group col-md-3">
			  	<%= f.label :min_weight, "Minimum Weight (lbs)" %>
			  	<%= f.number_field :min_weight, class: "form-control" %>
			  </div>

			  <div class="form-group col-md-3 col-md-offset-3">
			  	<%= f.label :max_weight, "Maximum Weight (lbs)" %>
			  	<%= f.number_field :max_weight, class: "form-control" %>
			  </div>
		  </div>

		  <%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>