config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users

  resources :brands do
    collection { post :import }
    resources :sizes, except: [:show] do
      collection { post :import }
    end
  end

  resources :sizes, only: [:destroy] do
    collection { post :import }
  end

  resources :size_imports, only: [:new, :create]

  get 'search/' =>'pages#search'

  get 'about/' => 'pages#about'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	extend FriendlyId
	extend CSVImportExport

	friendly_id :name, use: :slugged

	# Regular expressions

	VALID_URL_REGEX = /\Ahttps?:\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}\/*\z/ix
	INSTAGRAM_USERNAME_REGEX = /\A@{0,1}[\w]+\z/i

	# Validations

	validates :url,     presence: true, 
	                    format: { with: VALID_URL_REGEX } 
	validates :instagram_username, allow_nil: true,
																 allow_blank: true,
																 uniqueness: { case_sensitive: false },
	                               format: { with: INSTAGRAM_USERNAME_REGEX }
	
	# Callbacks

	before_validation :append_http
	before_save :remove_trailing_backslash
	before_save :remove_at_sign
	after_save :set_profile_picture

	has_many :sizes, dependent: :destroy

	def self.accessible_attributes
		%w[id name url slug instagram_username profile_picture]
	end

	def set_profile_picture
		return if !has_ig_username? || !instagram_username_changed?
		update_column(:profile_picture, ig_profile['profile_picture'])
	end

	def ig_profile
		client = ig_client
		profile = client.user_search(instagram_username, count: 1).first
		return profile
	end

	def ig_client
		Instagram.client(client_id: ENV['INSTAGRAM_CLIENT_ID'])
	end

	# Returns a Hashie:Mash of recent Instagram media tagged with
	# either the instagram username or the closest tag search result for
	# the brand name
	def ig_media
		if has_ig_username?
			tag = instagram_username
		else
			tag = find_ig_tag(name)
			return [] if tag.nil?
		end
		media = ig_client.tag_recent_media(tag)
	end

	# Returns a string representing the tag with the most media for
	# the given string. May be problematic if the string is a common word.
	def find_ig_tag(string)
		tags = ig_client.tag_search(usernameify(string))
		return nil if tags.empty?
		# Sort the tags by media count in descending order
		tags.sort { |t1, t2| t2.media_count <=> t1.media_count }
		tag = tags.first.name
		return tag
	end

	def has_ig_username?
		instagram_username && !instagram_username.blank?
	end

	# Removes non-word characters from a string

	def usernameify(username)
		username.gsub(/[\W]+/, "").downcase
	end

	private
		# Appends 'http://' to the url if not present
		def append_http
			return if url.nil?
			self.url = "http://#{self.url}" unless self.url[/\Ahttps?:\/\//]
		end

		def remove_trailing_backslash
			url.chop if url.last == "/"
		end

		def remove_at_sign
			instagram_username.slice!(0) if instagram_username && instagram_username.first == "@"
		end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	before_action :authenticate_user!, except: [:show]
	before_action :is_admin?, except: [:show]

	def new
		@brand = Brand.new()
	end

	def create
		@brand = Brand.new(brand_params)
		if @brand.save
			redirect_to brands_url
		else
			render 'new'
		end
	end

	def edit
		@brand = Brand.friendly.find(params[:id])
	end

	def update
		@brand = Brand.friendly.find(params[:id])
		if @brand.update_attributes(brand_params)
			flash[:success] = "Brand updated."
			redirect_to brands_url
		else
			render 'edit'
		end
	end

	def index
		@brands = Brand.all
		@size_import = SizeImport.new
		respond_to do |format|
			format.html { @brands = @brands.paginate(page: params[:page]) }
			format.csv do 
				send_data(@brands.to_csv)
			end
			format.xls
		end
	end

	def import
		Brand.import(params[:file])
		redirect_to brands_url
	end

	def destroy
		Brand.friendly.find(params[:id]).destroy
		redirect_to brands_url
	end

	def show
		@brand = Brand.friendly.find(params[:id])
		@sizes = @brand.sizes
		@feed_items = @brand.ig_media
	end

	private

		def brand_params
			params.require(:brand).permit(:name, :url, :instagram_username, :profile_picture)
		end
end

app/helpers/brands_helper.rb
module BrandsHelper
  def breaking_word_wrap(text, *args)
   options = args.extract_options!
   unless args.blank?
     options[:line_width] = args[0] || 80
   end
   options.reverse_merge!(line_width: 80)
   text = text.split(" ").collect do |word|
     word.length > options[:line_width] ? word.gsub(/(.{1,#{options[:line_width]}})/, "\\1 ") : word
   end * " "
   text.split("\n").collect do |line|
     line.length > options[:line_width] ? line.gsub(/(.{1,#{options[:line_width]}})(\s+|$)/, "\\1\n").strip : line
   end * "\n"
  end
end

app/views/brands/_brand.html.erb
<tr>
	<% %w[id name url].each do |name| %>
		<td>
			<%= brand.send(name).to_s %>
		</td>
	<% end %>
	<td>
		<%= link_to 'show', brand_path(brand) %>
		| <%= link_to 'edit', edit_brand_path(brand) %> 
		| <%= link_to 'delete', brand_path(brand), method: :delete, confirm: "Are you sure?" %>
	</td>
</tr>

app/views/brands/_feed_item.html.erb
<% unless feed_item.nil? %>
	<% caption = feed_item.caption %>
	<% image_url = feed_item.images.low_resolution.url %>
	<div class="feed_item col-md-4 col-sm-5 col-xs-10 col-xs-offset-1">
		<div class="feed_item thumbnail" 
				 data-toggle="tooltip" 
					<% if caption %>
					  title="@<%= caption.from.username %>: 
					        <%= breaking_word_wrap(caption.text, line_width: 35) %>"
					<% end %>
					        >
			<div class="feed_item_image">
				<%= image_tag image_url, height: 242, width: 242 %>
			</div>
			<div class="caption">
				<strong>@<%= feed_item.user.username %></strong> via Instagram
			</div>
		</div>
	</div>
<% end %>

app/views/brands/_fields.html.erb
<div class="form-group">
	<%= f.label :name, "Name" %>
	<%= f.text_field :name, autofocus: true, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :url, "Homepage URL" %>
	<%= f.text_field :url, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :instagram_username, "Instagram Username" %>
	<%= f.text_field :instagram_username, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :profile_picture, "Profile Picture URL" %>
	<%= f.text_field :profile_picture, class: "form-control" %>
</div>

app/views/brands/_import_brands_modal.html.erb
<%= button_tag 'Import brands', class: "btn btn-primary btn-lg", 
                                      "data-toggle" => "modal",
                                      "data-target" => '#import_brands' %>


<div class="modal fade" id="import_brands" tabindex="-1" 
     role="dialog" aria-labelledby="import_brands_label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="import_brands_label">Import Brands</h4>
      </div>
      <div class="modal-body">
        <%= form_tag import_brands_path, multipart: true do %>
        	<div class="form-group">
        		<%= file_field_tag :file %>
        	</div>
	        <%= button_tag "Close", class: "btn btn-default", 'data-dismiss' => 'modal' %>
        	<%= submit_tag "Import", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/brands/_import_sizes_modal.html.erb
<%= button_tag 'Import sizes', class: "btn btn-primary btn-lg",
                                     "data-toggle" => "modal",
                                     "data-target" => "#import_sizes" %>

<div class="modal fade" id="import_sizes" tabindex="-1" 
     role="dialog" aria-labelledby="import_sizes_label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="import_sizes_label">Import Brands</h4>
      </div>
      <div class="modal-body">
        <h2>Import Sizes</h2>
        <%= form_for @size_import, multipart: true do |f| %>
          <div class="form-group">
            <%= f.label :file %>
            <%= f.file_field :file %>
          </div>
          <%= button_tag "Cancel", class: "btn btn-default",
                                   "data-dismiss" => "modal" %>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/brands/_nav_tabs.html.erb
<ul class="nav nav-tabs">
	<li class="<%= "active" if params[:action] == 'index' %>">
		<%= link_to "List", brands_path %>
	</li>
	<li class="<%= "active" if params[:action] == 'new' %>">
		<%= link_to "Add", new_brand_path %>
	</li>
	<li class="dropdown">
		<a href="" class="dropdown-toggle" data-toggle="dropdown">
			Export <span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
			<li><%= link_to '.csv', brands_path(format: "csv") %></li>
			<li><%= link_to '.xls', brands_path(format: "xls") %></li>
		</ul>
	</li>
</ul>

app/views/brands/_size_table.html.erb
<table class="sizes table table-striped">
	<thead>
		<th>Size</th>
		<th>Height</th>
		<th>Weight</th>
	</thead>
	<tbody>
		<%= render @sizes %>
	</tbody>
</table>

app/views/brands/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2>Edit Brand</h2>
		<%= form_for @brand do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>
		  <%= render 'fields', f:f %>
		  <%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/brands/index.html.erb
<div class="row">
	<div class="col-md-8">
		<%= render "nav_tabs" %>
		<h2>Brands</h2>
		<table class="table table-striped">
			<thead>
				<% %w[id name url actions].each do |name| %>
					<th><%= name %></th>
				<% end %>
			</thead>
			<tbody>
				<%= render @brands %>
			</tbody>
		</table>
		<%= will_paginate @brands %>
	</div>
	<aside class="col-md-4">
		<div class="form-group">
			<%= render 'import_brands_modal' %>
		</div>
		<div class="form-group">
			<%= render 'import_sizes_modal' %>
		</div>
	</aside>
</div>

app/views/brands/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">URL</Data></Cell>
      </Row>
    <% @brands.each do |brand| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= brand.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= brand.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= brand.url %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/brands/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<%= render 'nav_tabs' %>
		<h2><%= params[:action].titleize %> Brand</h2>
		<%= form_for @brand do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

		  <%= render 'fields', f: f %>

		  <div class="form-group">
		  	<%= f.submit "Submit", class: "btn btn-primary" %>
		  </div>
		<% end %>
	</div>
</div>

app/views/brands/show.html.erb
<div class="row">
	<aside class="col-md-3">
		<% if @brand.profile_picture %>
			<%= image_tag @brand.profile_picture, alt: "#{@brand.name} logo",
			                                      height: 140,
			                                      width: 140 %>
		<% end %>
		<h1>
			<%= @brand.name %>
			<% if current_user && current_user.admin %>
				(<%= link_to 'edit', edit_brand_path(@brand) %>)
			<% end %>
		</h1>
		<h2>Sizes</h2>
		<% if @sizes.any? %>
			<%= render 'size_table' %>
		<% end %>
		<% if current_user && current_user.admin %>
			<h4>Actions</h4>
			<div>
				<%= link_to 'new', new_brand_size_path(@brand) %> |
			</div>
		<% end %>
	</aside>
	<div class="col-md-9">
		<div class="row">
			<% if @feed_items.any? %>
				<%= render partial: 'feed_item', as: :feed_item, collection: @feed_items %>
			<% end %>
		</div>
	</div>
</div>