config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users

  resources :brands do
    collection { post :import }
    resources :sizes, except: [:show] do
      collection { post :import }
    end
  end

  resources :sizes, only: [:destroy] do
    collection { post :import }
  end

  resources :size_imports, only: [:new, :create]

  get 'search/' =>'pages#search'

  get 'about/' => 'pages#about'

end

app/views/layouts/_footer.html.erb
<footer>
	<ul class="pull-right">
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", '#' %></li>
	</ul>	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" 
                            data-toggle="collapse" 
                            data-target="#header-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Gi Finder', root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="header-navbar-collapse-1">
<!--       <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                Admin <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Brands", brands_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown" id="dropdownMenu1">
              <span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "Profile", '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Create account', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div> -->
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>